### PR TITLE
Ignore file name in definitions when the folder and the filename matches

### PR DESCRIPTION
**Pull request by jonmanga**
Given a definition like `/star-wars/StarWars.yml` to output in generated definitions will only be `StarWars` instead of `StarWarsStarWars`

### CODE REVIEW

**Comment by johndcarmichael** [comment]
Not totally opposed to merging this in, but what is the use case? I mean, when would this happen?

**Comment by p-mcgowan** [comment]
does this only trim them when filename and dirname match?

for example, if we have `/star-wars/starWars.yml` but also `/star-wars/get.yml`, will 1 be `starWars` and the other `get`?

This may be something that should be configurable as opposed to one or the other - for example
```
  {{ autoDefinitionIndexer({ dropBaseName: true }) }}
```

**Comment by jonmanga** [comment]
@p-mcgowan  it's only for Models/Definitions. The trim will on act on the first instance. Instead of `StartWarsStarWars` you'll get `StartWars` in the second case you'll get `StarWarsGet`.

I didn't think anyone would want duplicate names in their models that's why I made it mandatory. However, we agreed with @johndcarmichael to make it configurable as you suggested above.

**Comment by p-mcgowan** [comment]
ah cool - yeah that makes sense

**Comment by jonmanga** [comment]
Update to use: 

```yml
{{ autoDefinitionIndexer({ dropBaseName: true }) }}
```

**Comment by johndcarmichael** [comment]
@jonmanga looks good except to make this easier for 3rd parties to understand and as this is not typescript could you add a jsdoc to the nunjucksHelpers/autoComponentIndexer.js then we can roll it out.

**Pull request merged**
