### PR TITLE
v2 release

### PR DESCRIPTION
**Pull request by johndcarmichael**
Includes the permission default options - not in a rush to see this role out as can just user 1.25.3 till it is out so if you see anything there is no rush to get it fixed. vnumber is already bumped to 2 in this pr.

The logo and the docs theme as also been updated

### CODE REVIEW

**Comment by johndcarmichael** [comment]
ok i'm happy with this from my perspective - to check on a project by npm install from github, post install cd to the folder, npm i, npm run build and for me i had to change the cli file to include from `require('../build/src/cli.js')` to `require('../build/cli.js')`

**Comment by johndcarmichael** [comment]
bug found with the permission config

**Comment by johndcarmichael** [comment]
bug above fixed

**Comment by johndcarmichael** [comment]
2.0.0-rc1.0 released to npm

**Comment by p-mcgowan** [comment]
Looks fine from an overview - later today I'll pull it down and run some tests and whatnot.

Still have not looked at the new docs but ill take a look then, and I would love to see travis passing for 2.0 so I'll take a whack at it

**Comment by p-mcgowan** [comment]
Tests still pass so that's great - 

What about ripping off the bandaid for 2.0 and adding a format step - `"format": "prettier --write '**/*.(ts|json)'"`?

I have a local config, and I think your editor has one as well, so it might be cool to have this automated.
```json
{
  "bracketSpacing": true,
  "endOfLine": "auto",
  "semi": true,
  "printWidth": 120,
  "singleQuote": true,
  "quoteProps": "consistent"
}
```

**Comment by johndcarmichael** [comment]
why not.. i think you might know that setup better than me though if you fancy putting it together?

been running this v2 release all day and so far no issues.. but yea if we could get travis sorted that would be nice. If any of the new github features include a test runner ci tool that could be better..

**Comment by p-mcgowan** [comment]
Ah true - if I strike out with travis I'll take a look at actions and toss in a prettier.

**Pull request merged**
